/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol PhotoScrubberDataSource
-(id)photoScrubber:(id)scrubber loadImageSynchronously:(BOOL)synchronously atIndex:(int)index forLoupe:(BOOL)loupe;
-(int)numPhotosInAlbumForPhotoScrubber:(id)photoScrubber;
@end

