/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import "NSObject.h"


@protocol PLAbstractAlbumPickerViewControllerDelegate <NSObject>
-(BOOL)albumPickerController:(id)controller shouldEnableAlbum:(NSObject*)album;
@end

