/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PLPhotoBrowserControllerDelegate <NSObject>
@optional
-(void)photoBrowserControllerDidEndPaging:(id)photoBrowserController;
-(void)photoBrowserControllerWillBeginPaging:(id)photoBrowserController;
-(void)photoBrowserController:(id)controller willShowActionSheetInView:(id)view;
-(BOOL)photoBrowserControllerShouldShowActionItem:(id)photoBrowserController;
-(void)photoBrowserController:(id)controller didMoveToPhotoAtIndex:(unsigned)index;
@end

