/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol PLPublishingAgentDelegate
-(void)publishingAgentDidEndPublishing:(id)publishingAgent error:(id)error;
-(void)publishingAgentDidBeginPublishing:(id)publishingAgent;
-(void)publishingAgentCancelButtonClicked:(id)clicked;
-(void)publishingAgentDoneButtonClicked:(id)clicked;
-(void)publishingAgentWillBeDisplayed:(id)publishingAgent;
@optional
-(void)publishingAgentDidEndRemaking:(id)publishingAgent didSucceed:(BOOL)succeed;
-(void)publishingAgentDidStartRemaking:(id)publishingAgent;
@end

