/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol PLSlideshowSettingsViewControllerDelegate
-(id)slideshowSettingsViewController:(id)controller slideshowSettingsForAirPlayService:(id)airPlayService;
-(id)slideshowSettingsViewController:(id)controller alternateTransitionLocalizationsForAirPlayService:(id)airPlayService;
-(id)slideshowSettingsViewController:(id)controller transitionKeysForAirPlayService:(id)airPlayService;
-(void)slideshowSettingsViewController:(id)controller didSelectAirPlayService:(id)service;
-(void)slideshowSettingsViewControllerPlayButtonWasPressed:(id)pressed;
@end

