/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PLStackViewDelegate <NSObject>
@optional
-(BOOL)stackViewShouldProcessTap:(id)stackView;
-(void)stackViewWillBeginDragging:(id)stackView;
-(void)stackViewSelectionDidChange:(id)stackViewSelection added:(id)added removed:(id)removed;
-(int)stackView:(id)view shouldEnableItemViewAtIndex:(int)index;
-(BOOL)stackView:(id)view shouldSelectItemAtIndex:(unsigned)index;
@end

