/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import "NSObject.h"

@class UIImageView;

@protocol PLStackableImage <NSObject>
@optional
@property(readonly, assign, nonatomic) CGRect frameOfImage;
@required
@property(readonly, assign, nonatomic) BOOL isBeingManipulated;
@property(assign, nonatomic) float transitionProgress;
@property(assign, nonatomic, getter=isShadowEnabled) BOOL shadowEnabled;
@property(readonly, assign, nonatomic) UIImageView* imageView;
@optional
-(void)renderSnapshotInContext:(CGContextRef)context;
-(void)setTextBadgeString:(id)string;
-(void)setSize:(CGSize)size angle:(float)angle;
-(void)expandWithAnimation:(BOOL)animation completion:(id)completion;
@end

