/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PLAssetContainer.h"

@class NSMutableOrderedSet;

@protocol PLUserEditableAssetContainer <PLAssetContainer>
@property(readonly, assign, nonatomic) NSMutableOrderedSet* userEditableAssets;
@end

