/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import "WConfigurableNavigationDisplayOptions.h"
#import "PLAbstractAlbumPickerViewControllerDelegate.h"
#import "PLActivityViewControllerDelegate.h"
#import "PLPhotosPickerSessionDelegate.h"
#import "PLStackViewDelegate.h"
#import "PLStackViewDataSource.h"
#import "UIActionSheetDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "PLSlideshowSettingsViewControllerDelegate.h"
#import "PLPhotosPickerSessionParticipant.h"
#import "PLAlbumChangeObserver.h"
#import "PLDismissableViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, PLStackView, PLPhotoScrubber, PLEmptyAlbumView, PLAlbumFooterView, PLLibraryBannerView, UINavigationItem, PLSegmentedControl, PLPhotosPickerSession, UIBarButtonItem, UIAlertView, NSArray, UIActionSheet, UIPopoverController, UINavigationController, PLVideoRemaker, PLActivityViewController, PLProgressView, NSObject, WAlbumPickerViewController, PLLibraryImageDataProvider, NSTimer, UIView, NSString, PLManagedAsset;
@protocol PLAssetContainer;

__attribute__((visibility("hidden")))
@interface WAlbumViewController : XXUnknownSuperclass <PLAbstractAlbumPickerViewControllerDelegate, PLActivityViewControllerDelegate, PLPhotosPickerSessionDelegate, PLStackViewDelegate, PLStackViewDataSource, UIActionSheetDelegate, UIPopoverControllerDelegate, PLSlideshowSettingsViewControllerDelegate, PLPhotosPickerSessionParticipant, PLAlbumChangeObserver, WConfigurableNavigationDisplayOptions, PLDismissableViewController> {
	NSObject* _album;
	PLStackView* _stackView;
	PLPhotoScrubber* _photoScrubber;
	PLEmptyAlbumView* _emptyAlbumView;
	PLAlbumFooterView* _footerView;
	PLLibraryBannerView* _bannerView;
	UIView* _customTitleView;
	NSString* _customTitle;
	int _currentFilter;
	BOOL _showPhotosVideosFilter;
	unsigned _ignoreReorderNotificationCount;
	BOOL _hasChangesInEditSession;
	BOOL _viewCountIsConsistentWithModel;
	PLPhotosPickerSession* _currentPickerSession;
	WAlbumPickerViewController* _albumPickerController;
	PLPhotosPickerSession* _activePhotosPickerSession;
	int _currentExpandedTag;
	UINavigationItem* _customNavigationItem;
	PLSegmentedControl* _filterControl;
	UIBarButtonItem* _playButtonItem;
	UIBarButtonItem* _actionButtonItem;
	UIBarButtonItem* _addButtonItem;
	UIBarButtonItem* _removeButtonItem;
	UIBarButtonItem* _cancelButtonItem;
	UIBarButtonItem* _savedBarButtonItem;
	UIBarButtonItem* _modalDoneButtonItem;
	UIAlertView* _createAlbumAlert;
	NSArray* _leftBarEditingItems;
	NSArray* _rightBarEditingItems;
	UIActionSheet* _moveSheet;
	UIActionSheet* _deleteWarningSheet;
	NSArray* _moveSheetActions;
	BOOL _isSlideShowScheduled;
	UIView* _fadeToBlackView;
	BOOL _fadingToBlack;
	BOOL _slideshowIsOrigami;
	UIPopoverController* _slideshowSettingsPopover;
	UIPopoverController* _activityControllerPopover;
	unsigned _remaking : 1;
	int _selectedImageCount;
	int _selectedAVCount;
	int _selectedUnknownCount;
	int _selectedPlaceholderCount;
	NSDictionary* _trimDictionary;
	UINavigationController* _composeNavigationController;
	unsigned _dataInsertionCount;
	unsigned _trimmingForMMS : 1;
	PLVideoRemaker* _remaker;
	SEL _completionSelector;
	PLManagedAsset* _currentVideo;
	PLActivityViewController* _activityViewController;
	PLProgressView* _progressView;
	NSTimer* _progressUpdateTimer;
	BOOL _shouldReloadWhenBecomingVisible;
	id _nextViewDidLayoutSubviewsHandler;
	BOOL _shouldShowEmptyAlbumView;
	unsigned _programmaticExpansion : 1;
	id _activityTarget;
	SEL _activityAction;
	PLLibraryImageDataProvider* imageDataProvider;
}
@property(copy) NSString* customTitle;
@property(retain) UIView* customTitleView;
@property(retain, nonatomic) PLPhotosPickerSession* currentPickerSession;
@property(copy, nonatomic) NSArray* selectedPhotos;
@property(assign, nonatomic) BOOL shouldShowEmptyAlbumView;
@property(retain, nonatomic) PLStackView* stackView;
@property(retain, nonatomic) PLLibraryImageDataProvider* imageDataProvider;
@property(assign, nonatomic) int currentFilter;
@property(assign, nonatomic) BOOL showPhotosVideosFilter;
@property(retain, nonatomic) NSObject<PLAssetContainer>* album;
@property(assign, nonatomic) BOOL hasChangesInEditSession;
-(void)videoRemakerDidEndRemaking:(id)videoRemaker temporaryPath:(id)path;
-(void)_remakerDidFinish:(id)_remaker;
-(void)videoRemakerDidBeginRemaking:(id)videoRemaker;
-(void)_showMailComposition:(id)composition transcodedVideoPath:(id)path;
-(void)_showMailComposition:(id)composition;
-(void)editVideoViewControllerDidCancel:(id)editVideoViewController;
-(void)editVideoViewController:(id)controller didTrimVideoWithOptions:(id)options;
-(void)_transcodeVideo:(id)video usingMode:(int)mode completionSelector:(SEL)selector;
-(void)_showTrimViewControllerForVideo:(id)video maximumTrimDuration:(double)duration trimButtonTitle:(id)title;
-(void)_showRemakerProgressView:(BOOL)view;
-(BOOL)popControllerWhenStackCollapses;
-(BOOL)canSaveToCameraRoll;
-(BOOL)canDeletePhotos;
-(BOOL)canRemovePhotos;
-(id)removableSelectedPhotos;
-(id)contentScrollView;
-(id)filteredItems;
-(id)_library;
-(BOOL)photosPickerSessionShouldFinishWithCurrentSelection:(id)photosPickerSession;
-(void)_restoreSelectionFromPickerSession;
-(id)navigationItem;
-(id)navigationBar;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)updateFooterView;
-(void)getDisplayPhotoCount:(unsigned*)count videoCount:(unsigned*)count2 pendingCount:(unsigned*)count3 importOperation:(int*)operation;
-(id)_footerSubtitle;
-(void)libraryDidChange:(id)library;
-(void)albumDidChange:(id)album;
-(void)smsComposeControllerSendStarted:(id)started;
-(void)smsComposeControllerCancelled:(id)cancelled;
-(void)smsComposeControllerAppeared:(id)appeared;
-(void)smsComposeControllerDataInserted:(id)inserted;
-(void)expandableViewDidCompleteExpanding:(id)expandableView;
-(void)expandableViewWillBeginExpanding:(id)expandableView;
-(id)expandedControllerForExpandableView:(id)expandableView;
-(void)_imageViewDidCompleteExpanding:(id)_imageView;
-(void)stackViewSelectionDidChange:(id)stackViewSelection added:(id)added removed:(id)removed;
-(void)beginPoppingAnimated:(BOOL)animated completionHandler:(id)handler;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
-(id)slideshowSettingsViewController:(id)controller slideshowSettingsForAirPlayService:(id)airPlayService;
-(id)slideshowSettingsViewController:(id)controller alternateTransitionLocalizationsForAirPlayService:(id)airPlayService;
-(id)slideshowSettingsViewController:(id)controller transitionKeysForAirPlayService:(id)airPlayService;
-(void)slideshowSettingsViewController:(id)controller didSelectAirPlayService:(id)service;
-(void)slideshowSettingsViewControllerPlayButtonWasPressed:(id)pressed;
-(BOOL)prepareForDismissingAnimated:(BOOL)dismissingAnimated;
-(void)performBlockAfterNextViewDidLayoutSubviews:(id)performBlockAfterNextView;
-(void)scrollToRevealPhoto:(id)revealPhoto animated:(BOOL)animated;
-(void)expandImageViewForPhoto:(id)photo toComment:(id)comment animated:(BOOL)animated;
-(void)expandImageViewForPhoto:(id)photo animated:(BOOL)animated;
-(void)_dismissSlideshowPopover;
-(void)_dismissSlideshowPopoverAnimated:(BOOL)animated;
-(void)_showSlideshowSettings:(id)settings;
-(void)_beginSlideshow;
-(void)_fadeToBlackAnimation:(id)blackAnimation finished:(id)finished context:(void*)context;
-(void)_fadeToBlack;
-(BOOL)albumPickerController:(id)controller shouldEnableAlbum:(id)album;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)stackView:(id)view getUnreadStartMarkerCount:(unsigned*)count showsProgress:(BOOL*)progress;
-(BOOL)stackView:(id)view writeItemsWithIndexes:(id)indexes toPasteboard:(id)pasteboard;
-(void)stackViewItemMoveDidComplete:(id)stackViewItemMove;
-(void)stackView:(id)view moveItemAtIndex:(unsigned)index toIndex:(unsigned)index3;
-(int)stackView:(id)view editingOptionsForItemAtIndex:(unsigned)index;
-(id)stackView:(id)view collapsedIndexesForCount:(unsigned)count;
-(void)stackView:(id)view saveStackedImage:(id)image options:(id)options;
-(id)stackedImageForStackView:(id)stackView options:(id*)options;
-(int)stackViewPosterItemIndex:(id)index;
-(id)stackView:(id)view badgeImageForImageAtIndex:(int)index;
-(id)stackView:(id)view textBadgeStringForImageAtIndex:(int)index;
-(void)stackView:(id)view preheatImagesInRange:(NSRange)range;
-(BOOL)stackViewPrefersLazyPreheating:(id)preheating;
-(id)stackView:(id)view dataForImageAtIndex:(int)index imageData:(XXStruct_g6RH7D*)data;
-(id)stackView:(id)view itemViewAtIndex:(int)index loadImagesSynchronously:(BOOL)synchronously;
-(int)stackViewItemCount:(id)count;
-(void)_showMoveSheet:(id)sheet;
-(void)_publishingAgentDidEndRemaking:(id)_publishingAgent;
-(void)_publishingAgentDidStartRemaking:(id)_publishingAgent;
-(void)_updateProgressView;
-(id)_currentPublishingAgent;
-(void)activityViewControllerDidDismiss:(id)activityViewController;
-(void)_displayActivitySheet:(id)sheet;
-(void)_dismissActivityControllerPopover:(BOOL)popover;
-(void)_performPostAlbumStreamTasksWithNewlyCreatedAlbum:(NSObject*)newlyCreatedAlbum;
-(void)_addAssets:(id)assets;
-(void)_updateBannerSelectionButton;
-(void)_updateAddButtonTitleAndAction;
-(void)_updateNavigationBarAnimated:(BOOL)animated;
-(void)_reclaimImageView:(id)view;
-(void)reclaimStackView;
-(BOOL)_canAddToAssets;
-(void)_updateUnreadMarkerAnimated:(BOOL)animated;
-(BOOL)_dismissPopovers;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(void)_showMMSCompositionForVideo:(id)video startTime:(double)time endTime:(double)time3;
-(void)_showTextMessageComposition:(id)composition;
-(void)_sendViaMMS:(id)mms;
-(void)_addSelectionToNewAlbum:(id)newAlbum;
-(void)deleteSelection:(id)selection;
-(void)copySelection:(id)selection;
-(void)paste:(id)paste;
-(void)copy:(id)copy;
-(void)emailSelection:(id)selection;
-(void)saveSelection:(id)selection;
-(id)_editButtons;
-(void)_updateStackView;
-(void)_endSelectionMode:(BOOL)mode;
-(void)_beginSelectionMode;
-(void)_endEditing:(id)editing;
-(void)_beginEditing:(id)editing;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_filterWasToggled:(id)toggled;
-(void)showEmptyAlbumView:(BOOL)view;
-(void)_resizeFilterControlForInterfaceOrientation:(int)interfaceOrientation;
-(id)_suppresionContexts;
-(BOOL)_appAllowsSupressionOfAlerts;
-(void)interactionCancelledWithView:(id)view;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappearInteractivelyWithView:(id)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidAppearInteractivelyWithView:(id)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillAppearInteractivelyWithView:(id)view;
-(void)viewDidLoad;
-(void)loadView;
-(void)_getRotationContentSettings:(XXStruct_3uUjXA*)settings;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(id)initWithAlbum:(NSObject*)album imageDataProvider:(id)provider;
-(id)initWithAlbum:(NSObject*)album imageDataProvider:(id)provider modalDoneButtonItem:(id)item;
@end

