/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class WLibraryViewController, WInteractiveNavigationController;

__attribute__((visibility("hidden")))
@interface WAlbumPickerViewController : XXUnknownSuperclass {
	WInteractiveNavigationController* _navController;
}
@property(readonly, assign, nonatomic) WLibraryViewController* libraryViewController;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)animateBannerThumbnailToAlbumAtIndex:(unsigned)index completion:(id)completion;
-(int)bannerViewStyle;
-(int)albumListFilter;
-(id)preparedLibraryViewController;
-(void)setAlbumCreationLabel:(id)label;
-(void)_updateBannerViewButton;
-(id)preparedContentController;
-(void)dealloc;
-(id)initWithLibraryContentMode:(int)libraryContentMode assetsToAdd:(id)add completionHandler:(id)handler;
@end

