/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import "WAlbumViewController.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface WAllPhotosAlbumViewController : WAlbumViewController {
	struct {
		unsigned expandingItemImagesLoadSynchronously : 1;
		unsigned unused : 31;
	} _flags;
	NSArray* _syncProgressAlbums;
}
-(id)_syncProgressAlbums;
-(void)getDisplayPhotoCount:(unsigned*)count videoCount:(unsigned*)count2 pendingCount:(unsigned*)count3 importOperation:(int*)operation;
-(void)setExpandingItemImagesLoadSynchronously:(BOOL)synchronously;
-(BOOL)popControllerWhenStackCollapses;
-(void)reclaimStackView;
-(void)albumDidChange:(id)album;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithAlbum:(NSObject*)album imageDataProvider:(id)provider;
@end

