/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIView, NSString;

@protocol WConfigurableNavigationDisplayOptions <NSObject>
@property(copy) NSString* customTitle;
@property(retain) UIView* customTitleView;
@end

