/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WInteractiveNavigationControllerDelegate <NSObject>
@optional
-(void)interactiveNavigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)interactiveNavigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
@end

