/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Camera-Structs.h"
#import "PLExpandableViewDelegate.h"

@class UIViewController, NSMutableArray, PLExpandableView, UIView, WInteractiveNavigationControllerView;
@protocol WInteractiveNavigationControllerDelegate;

__attribute__((visibility("hidden")))
@interface WInteractiveNavigationController : XXUnknownSuperclass <PLExpandableViewDelegate> {
	NSMutableArray* _stack;
	WInteractiveNavigationControllerView* _contentView;
	UIView* _interactiveView;
	UIView* _overlayView;
	UIView* _headerView;
	UIViewController* _previousViewController;
	UIViewController* _expandedController;
	PLExpandableView* _expandingView;
	NSMutableArray* _navBarPushPopQueue;
	double _lastAlphaTime;
	struct {
		unsigned operation : 3;
		unsigned visible : 1;
		unsigned programmaticPopInProgress : 1;
		unsigned finishingCurrentOperation : 1;
		unsigned previousControllerWasEditing : 1;
		unsigned propagateEditingMode : 1;
	} _stackFlags;
	struct {
		unsigned blockAppearanceCallbacks : 1;
		unsigned inExplicitAppearanceTransition : 1;
	} _appearanceFlags;
	id<WInteractiveNavigationControllerDelegate> delegate;
}
@property(assign, nonatomic) BOOL shouldPropagateEditingMode;
@property(assign, nonatomic, getter=headerViewIsHidden) BOOL headerViewHidden;
@property(retain, nonatomic) UIView* headerView;
@property(assign, nonatomic, getter=footerViewIsHidden) BOOL footerViewHidden;
@property(retain, nonatomic) UIView* footerView;
@property(assign, nonatomic) id<WInteractiveNavigationControllerDelegate> delegate;
-(id)viewControllers;
-(id)topViewController;
-(id)bottomViewController;
-(void)setFooterViewHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setHeaderViewHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)navigationBar:(id)bar didPopItem:(id)item;
-(void)navigationBar:(id)bar didPushItem:(id)item;
-(void)_processNavBarPushPopQueue;
-(BOOL)navigationBar:(id)bar shouldPopItem:(id)item;
-(void)_notifyAction:(SEL)action expandableView:(id)view duration:(double)duration;
-(void)_notifyAction:(SEL)action expandableView:(id)view;
-(void)_setInteractiveController:(id)controller interactiveView:(id)view;
-(void)expandableView:(id)view expansionFractionChanged:(float)changed;
-(void)expandableViewDidCancelCollapsing:(id)expandableView;
-(void)expandableView:(id)view willCancelCollapsingWithDuration:(double)duration;
-(void)expandableViewDidCompleteCollapsing:(id)expandableView;
-(void)expandableView:(id)view willCompleteCollapsingWithDuration:(double)duration;
-(void)expandableViewDidBeginCollapsing:(id)expandableView;
-(void)expandableViewDidCancelExpanding:(id)expandableView;
-(void)expandableView:(id)view willCancelExpandingWithDuration:(double)duration;
-(void)expandableViewDidCompleteExpanding:(id)expandableView;
-(void)expandableView:(id)view willCompleteExpandingWithDuration:(double)duration;
-(void)expandableViewWillBeginExpanding:(id)expandableView;
-(void)_getRotationContentSettings:(XXStruct_3uUjXA*)settings;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(id)rotatingFooterView;
-(id)rotatingHeaderView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated completion:(id)completion;
-(void)popToRootViewController;
-(void)popViewControllerAnimated:(BOOL)animated completion:(id)completion;
-(void)popToViewController:(id)viewController;
-(void)popViewController;
-(BOOL)isPoppingViewController;
-(BOOL)isPushingViewController;
-(void)cancelPoppingViewController;
-(void)cancelPushingViewController;
-(void)_finishCurrentOperationBeforePushingViewController:(id)controller;
-(void)_finishCurrentOperation;
-(void)finishPoppingViewController;
-(void)finishPushingViewController;
-(BOOL)_validateOperation:(int)operation errorString:(id)string;
-(void)_finishedAnimatingTopAlpha:(id)alpha finished:(id)finished topItem:(id)item;
-(void)setTransitionProgress:(float)progress withDuration:(double)duration;
-(void)_performNavBarPushPop:(int)pop transition:(int)transition;
-(void)setTopViewControllerAlpha:(float)alpha;
-(BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
-(void)beginPoppingViewControllerInteractivelyUsingView:(id)view;
-(void)beginPushingViewController:(id)controller interactivelyUsingView:(id)view;
-(void)_setOverlayView:(id)view;
-(void)_setInteractiveView:(id)view;
-(void)_setPreviousViewController:(id)controller;
-(void)replaceTopViewControllerWithViewController:(id)viewController;
-(void)_removeTopViewController;
-(void)_addViewController:(id)controller;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)viewControllerNavigationItems;
-(id)navigationBar;
-(id)_contentView;
-(void)loadView;
-(void)dealloc;
-(id)initWithRootViewController:(id)rootViewController;
-(id)init;
-(BOOL)pl_behavesLikeNavigationControllerForNotifications;
@end

