/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import <PhotoLibraryServices/PLPhotoStreamsHelper.h>
#import "UINavigationBarDelegate.h"

@class UIView, UINavigationBar;

__attribute__((visibility("hidden")))
@interface WInteractiveNavigationControllerView : PLPhotoStreamsHelper <UINavigationBarDelegate> {
	UIView* _top;
	UIView* _bottom;
	UIView* _interactive;
	UIView* _overlay;
	UINavigationBar* _navBar;
	UIView* _header;
	UIView* _footer;
	int _orientation;
	struct {
		unsigned transitioning : 1;
		unsigned headerViewIsVisible : 1;
		unsigned footerViewIsVisible : 1;
	} _controllerViewFlags;
}
@property(assign, nonatomic, getter=footerViewIsHidden) BOOL footerViewHidden;
@property(assign, nonatomic, getter=headerViewIsHidden) BOOL headerViewHidden;
@property(retain, nonatomic) UIView* footerView;
@property(retain, nonatomic) UIView* headerView;
@property(retain, nonatomic) UIView* bottomView;
@property(retain, nonatomic) UIView* topView;
@property(readonly, assign, nonatomic) UINavigationBar* navigationBar;
-(void)setInterfaceOrientation:(int)orientation;
-(void)setTopViewAlpha:(float)alpha;
-(void)setOverlayView:(id)view;
-(id)interactiveView;
-(void)setInteractiveView:(id)view;
-(void)setInteractiveView:(id)view removePrevious:(BOOL)previous;
-(void)transitionDidEnd;
-(void)transitionWillBegin;
-(void)layoutSubviews;
-(void)_adjustViewFrame:(id)frame;
-(void)setFooterViewHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setHeaderViewHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

