/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Camera-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "PLStackableImage.h"

@class NSObject;
@protocol PLAssetContainer;

__attribute__((visibility("hidden")))
@interface WNestableStackView : XXUnknownSuperclass <PLStackableImage> {
	NSObject* album;
	NSObject* filteredAlbum;
}
@property(retain, nonatomic) NSObject<PLAssetContainer>* filteredAlbum;
@property(assign, nonatomic) NSObject<PLAssetContainer>* album;
-(CGRect)frameOfImage;
-(BOOL)isBeingManipulated;
-(float)transitionProgress;
-(void)setTransitionProgress:(float)progress;
-(BOOL)isShadowEnabled;
-(void)setShadowEnabled:(BOOL)enabled;
-(id)imageView;
-(void)dealloc;
@end

