/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <PhotoLibraryServices/_PLNetworkReachabilityIsOnWiFiKey.h>
#import "WInteractiveNavigationControllerDelegate.h"
#import "PLPhotoBrowserControllerDelegate.h"


__attribute__((visibility("hidden")))
@interface WPadCameraPageController : _PLNetworkReachabilityIsOnWiFiKey <WInteractiveNavigationControllerDelegate, PLPhotoBrowserControllerDelegate> {
}
-(void)interactiveNavigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)interactiveNavigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(id)_pagingPhotoBrowser;
-(void)prepareAlbumNavigationControllerForReuse:(id)reuse;
-(id)newAlbumNavigationController;
-(void)dealloc;
@end

