/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (InteractiveStacking)
-(id)expandedControllerForExpandableView:(id)expandableView;
-(void)hidePopoverView;
-(id)overlayView;
-(void)beginPoppingAnimated:(BOOL)animated completionHandler:(id)handler;
-(id)interactiveNavigationControllerIfTop;
-(id)interactiveNavigationController;
-(void)interactionCancelledWithView:(id)view;
-(void)interactiveNavigationControllerDidFinishWithOverlayView:(id)interactiveNavigationController;
-(void)viewDidDisappearInteractivelyWithView:(id)view;
-(void)viewDidAppearInteractivelyWithView:(id)view;
-(void)viewWillAppearInteractivelyWithView:(id)view;
@end

@interface XXUnknownSuperclass (Testing)
-(id)_cameraView;
@end

